spring.application.name=api
server.port=8080

# Configuracion para la conexion a la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/BD_DentalCareWeb?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate crea tablas automaticamente
spring.jpa.hibernate.ddl-auto=update
# Esta destruye y crea las tablas automaticamente cada vez que se inicia la app
# spring.jpa.hibernate.ddl-auto=create-drop
# Esta permite hacer validaciones de las tablas que se van a crear
# spring.jpa.hibernate.ddl-auto=validate

# Configuraciones extra de JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
